# Generated by Django 4.2.1 on 2023-05-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('job_ref', models.CharField(max_length=20)),
                ('job_description', models.TextField()),
                ('reports_to', models.CharField(max_length=100)),
                ('requirements', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_open', models.DateField()),
                ('date_closed', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
