# Generated by Django 4.2.1 on 2023-05-20 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='application_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
