# Generated by Django 4.2.1 on 2023-05-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_jobapplication_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_shortlisted',
            field=models.BooleanField(default=False),
        ),
    ]
