# Generated by Django 4.2.1 on 2023-05-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0005_shortlistedapplicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='is_shortlisted',
        ),
        migrations.DeleteModel(
            name='ShortlistedApplicant',
        ),
    ]
