# Generated by Django 4.2.1 on 2023-05-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0005_examiningbody_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examiningbody',
            name='certificate',
        ),
    ]
