# Generated by Django 4.2.1 on 2023-05-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0006_remove_jobapplication_is_shortlisted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_qualified',
            field=models.BooleanField(default=False),
        ),
    ]
