# Generated by Django 4.2.1 on 2023-05-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0007_jobapplication_is_qualified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='is_qualified',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_shortlisted',
            field=models.BooleanField(default=False),
        ),
    ]
