# Generated by Django 4.2.1 on 2023-05-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0008_remove_jobapplication_is_qualified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='is_shortlisted',
        ),
    ]
