# Generated by Django 4.2.1 on 2023-05-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0008_academicdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdetails',
            name='end_year',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='start_year',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
