# Generated by Django 4.2.1 on 2023-05-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0009_alter_academicdetails_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdetails',
            name='start_year',
            field=models.PositiveIntegerField(blank=True, default=2023, null=True),
        ),
    ]
