# Generated by Django 4.2.1 on 2023-05-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0009_remove_jobapplication_is_shortlisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='shortlisted',
            field=models.BooleanField(default=False),
        ),
    ]
