# Generated by Django 4.2.1 on 2023-05-21 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0010_jobapplication_shortlisted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='shortlisted',
            new_name='is_qualified',
        ),
    ]
