# Generated by Django 4.2.1 on 2023-05-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0010_alter_academicdetails_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdetails',
            name='admission_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='institution_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='start_year',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
