# Generated by Django 4.2.1 on 2023-05-22 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0011_rename_shortlisted_jobapplication_is_qualified'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualifiedApplicant',
            fields=[
                ('job_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='applicants.jobapplication')),
                ('applicant_name', models.CharField(max_length=100)),
                ('applied_vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicants.vacancy')),
            ],
        ),
    ]
