# Generated by Django 4.2.1 on 2023-05-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0011_alter_academicdetails_admission_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdetails',
            name='end_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='graduation_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='start_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
