# Generated by Django 4.2.1 on 2023-05-17 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0013_alter_academicdetails_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdetails',
            name='admission_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='end_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='graduation_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='start_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RelevantCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('completion_date', models.DateField()),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicants.examiningbody')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
