# Generated by Django 4.2.1 on 2023-05-17 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0014_alter_academicdetails_admission_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
