# Generated by Django 4.2.1 on 2023-05-23 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0014_vacancytype_vacancy_vacancy_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='date_closed',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='vacancy_documents/'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='academic_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicants.academiclevel'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='area_of_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicants.areaofstudy'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='reports_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicants.specialization'),
        ),
    ]
