# Generated by Django 4.2.1 on 2023-05-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0015_alter_academicdetails_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relevantcourse',
            old_name='provider',
            new_name='certification',
        ),
        migrations.AddField(
            model_name='relevantcourse',
            name='institution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='relevantcourse',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relevantcourse',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
