# Generated by Django 4.2.1 on 2023-05-23 12:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0017_alter_vacancy_job_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='job_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
