# Generated by Django 4.2.1 on 2023-05-23 12:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0018_alter_vacancy_job_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='job_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
