# Generated by Django 4.2.1 on 2023-05-18 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0018_referee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referee',
            old_name='position',
            new_name='occupation',
        ),
    ]
