# Generated by Django 4.2.1 on 2023-05-18 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0019_rename_position_referee_occupation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referee',
            old_name='Relationship_period',
            new_name='relationship_period',
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(blank=True, max_length=100, null=True)),
                ('admission_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('start_year', models.DateField(blank=True, null=True)),
                ('end_year', models.DateField(blank=True, null=True)),
                ('graduation_year', models.DateField(blank=True, null=True)),
                ('course_name', models.CharField(max_length=100)),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('company_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('position_description', models.TextField()),
                ('employment_start_date', models.DateField()),
                ('employment_end_date', models.DateField()),
                ('referee_name', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('relationship_period', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('academic_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicants.academiclevel')),
                ('area_of_study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicants.areaofstudy')),
                ('certification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_certification', to='applicants.examiningbody')),
                ('examining_body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_examining_body', to='applicants.examiningbody')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicants.specialization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
