# Generated by Django 4.2.1 on 2023-05-25 12:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0019_alter_vacancy_job_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicdetails',
            name='is_studying',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='responsibilities',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
