# Generated by Django 4.2.1 on 2023-05-18 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0021_alter_employmenthistory_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='academic_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', related_query_name='resume', to='applicants.academicdetails'),
        ),
        migrations.AddField(
            model_name='resume',
            name='employment_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', related_query_name='resume', to='applicants.employmenthistory'),
        ),
        migrations.AddField(
            model_name='resume',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', related_query_name='resume', to='applicants.referee'),
        ),
        migrations.AddField(
            model_name='resume',
            name='relevant_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', related_query_name='resume', to='applicants.relevantcourse'),
        ),
    ]
