# Generated by Django 4.2.1 on 2023-05-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0022_alter_customuser_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_organization_staff',
            field=models.BooleanField(default=False),
        ),
    ]
