# Generated by Django 4.2.1 on 2023-05-19 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0023_remove_resume_employment_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='academic_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicants.academiclevel'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='area_of_study',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicants.areaofstudy'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicants.specialization'),
        ),
    ]
