# Generated by Django 4.2.1 on 2023-05-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0024_vacancy_academic_level_vacancy_area_of_study_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='number_of_vacancies',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
