# Generated by Django 4.2.1 on 2023-05-31 13:12

import applicants.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0024_emailtemplate_delete_qualifiedapplicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='cv',
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(upload_to=applicants.models.certificate_upload_to)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='documents',
            field=models.ManyToManyField(to='applicants.document'),
        ),
    ]
