# Generated by Django 4.2.1 on 2023-05-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0025_vacancy_department_vacancy_number_of_vacancies'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
