# Generated by Django 4.2.1 on 2023-05-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0025_remove_jobapplication_cv_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='certificate',
            field=models.FileField(upload_to='certificates/'),
        ),
    ]
