# Generated by Django 4.2.1 on 2023-05-31 14:24

import applicants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0026_alter_document_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='certificate',
            field=models.FileField(upload_to=applicants.models.certificate_upload_to),
        ),
    ]
