# Generated by Django 4.2.1 on 2023-06-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0027_alter_document_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='is_filled',
            field=models.BooleanField(default=False),
        ),
    ]
