# Generated by Django 4.2.1 on 2023-06-06 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0028_vacancy_is_filled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='documents',
        ),
    ]
