# Generated by Django 4.2.1 on 2023-06-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0029_remove_jobapplication_documents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='certificate',
            new_name='document',
        ),
    ]
