# Generated by Django 4.2.1 on 2023-06-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0031_customuser_is_person_with_disability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='response',
            field=models.TextField(blank=True),
        ),
    ]
