# Generated by Django 4.2.6 on 2023-11-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0033_delete_emailtemplate_and_more'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='EmailTemplate',
        # ),
        # migrations.AddField(
        #     model_name='employmenthistory',
        #     name='currently_working_here',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='relevantcourse',
        #     name='is_studying',
        #     field=models.BooleanField(default=False),
        # ),
        migrations.AddField(
            model_name='vacancy',
            name='min_experience_years',
            field=models.PositiveIntegerField(
                blank=True, help_text='Minimum years of experience required', null=True),
        ),
        # migrations.AlterField(
        #     model_name='vacancy',
        #     name='job_name',
        #     field=models.CharField(max_length=200),
        # ),
        # migrations.AlterField(
        #     model_name='vacancy',
        #     name='job_ref',
        #     field=models.CharField(max_length=200),
        # ),
        # migrations.AlterField(
        #     model_name='vacancy',
        #     name='reports_to',
        #     field=models.CharField(blank=True, max_length=200, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='vacancytype',
        #     name='name',
        #     field=models.CharField(max_length=200),
        # ),
    ]
