# Generated by Django 4.2.1 on 2023-08-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0033_delete_emailtemplate_alter_vacancy_job_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relevantcourse',
            name='is_studying',
            field=models.BooleanField(default=False),
        ),
    ]
