# Generated by Django 4.2.1 on 2023-08-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0034_relevantcourse_is_studying'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmenthistory',
            name='currently_working_here',
            field=models.BooleanField(default=False),
        ),
    ]
