# Generated by Django 4.2.6 on 2023-11-18 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0036_delete_emailtemplate_and_more'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='EmailTemplate',
        # ),
        # migrations.AddField(
        #     model_name='employmenthistory',
        #     name='currently_working_here',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='relevantcourse',
        #     name='is_studying',
        #     field=models.BooleanField(default=False),
        # ),
        migrations.AlterField(
            model_name='academicdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='AcademicDetails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='EmploymentHistory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='Referee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relevantcourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='Relevantcourse', to=settings.AUTH_USER_MODEL),
        ),
        # migrations.AlterField(
        #     model_name='vacancy',
        #     name='job_name',
        #     field=models.CharField(max_length=200),
        # ),
        # migrations.AlterField(
        #     model_name='vacancy',
        #     name='job_ref',
        #     field=models.CharField(max_length=200),
        # ),
        # migrations.AlterField(
        #     model_name='vacancy',
        #     name='reports_to',
        #     field=models.CharField(blank=True, max_length=200, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='vacancytype',
        #     name='name',
        #     field=models.CharField(max_length=200),
        # ),
    ]
